admin_config:
  summary: This API group is related to the config management function.
  put:
    tags:
      - config
    operationId: configUpdate
    summary: Update the VDL config
    description: |- 
      Update the VDL config.
      <ul>
        <li>If an error occurs, the config will not be updated.</li>
      </ul>
      Request example: PUT /api/v1/admin/config
    responses:
      '204':
        description: Responds that the resource was able to be updated.
      '400':
        description: The required parameters for the request do not exist, or the input format is invalid.
        content:
          text/plain:
            schema:
              type: string
            example: Request is invalid.
      '401':
        description: No ID token or access token specified or If the discovery endpoint specified by "iss" in the token is not present in the configuration file.
        content:
          text/plain:
            schema:
              type: string
            example: Failed to authenticate.
      '403':
        description: Authorization function returned NG as an authorization decision result.
        content:
          text/plain:
            schema:
              type: string
              example: Operation not permitted.
      '404':
        description: |-
          The target resource does not exist.<br>
          Authorization function returned NG as an authorization decision result.
        content:
          text/plain:
            schema:
              type: string
            example: Requested resource not found.
      '500':
        description: An error occurred in the server's internal processing.
