# 2025/02/25にリクエストされるデータ群
testdata:
  flushData: false
  data: []
  randomDataOutputDir: "./data/"
  # 個別設定で上書きするため以下の2つは使われない
  randomDataBaseTime: "2025-01-28T10:00:00+09:00"
  randomDataDuration: 1h
  randomData:
    - id: "C4_202502251000_1"
      name: "気象情報:（2/26(水) 06:00-06:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T06:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "300"
        windSpeed: "0.0"
        precipitation: "50.0"
    - id: "C4_202502251000_2"
      name: "気象情報:（2/26(水) 07:00-08:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T07:00:00+09:00"
      duration: 2h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    # 11:00, 12:00, 13:00のリクエスト向けデータ
    - id: "C4_202502251100_0"
      name: "気象情報:（2/25(火) 14:00-16:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-25T14:00:00+09:00"
      duration: 3h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    - id: "C4_202502251100_1"
      name: "気象情報:（2/26(水) 10:00-10:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T10:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "15.0"
        precipitation: "0.0"
    - id: "C4_202502251100_2"
      name: "気象情報:（2/26(水) 11:00-12:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T11:00:00+09:00"
      duration: 2h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    - id: "C4_202502251200_1"
      name: "気象情報:（2/26(水) 14:00-14:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T14:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "300"
        windSpeed: "0.0"
        precipitation: "25.0"
    # 12:00, 18:00のリクエスト向けデータ
    - id: "C4_202502251200_2"
      name: "気象情報:（2/26(水) 15:00-18:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T15:00:00+09:00"
      duration: 4h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    # 19:00, 20:00のリクエスト向けデータ
    - id: "C4_202502251900"
      name: "気象情報:（2/25(火) 22:00-24:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-25T22:00:00+09:00"
      duration: 3h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
