# 2025/02/13にリクエストされるデータ群
testdata:
  flushData: false
  data: []
  randomDataOutputDir: "./data/"
  # 個別設定で上書きするため以下の2つは使われない
  randomDataBaseTime: "2025-01-28T10:00:00+09:00"
  randomDataDuration: 1h
  randomData:
    # 9:00, 16:00のリクエストデータ
    - id: "C4_202502130900_1"
      name: "気象情報:（2/26(水) 06:00-08:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T06:00:00+09:00"
      duration: 3h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    - id: "C4_202502130900_2"
      name: "気象情報:（2/26(水) 09:00-09:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T09:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "300"
        windSpeed: "0.0"
        precipitation: "50.0"
    - id: "C4_202502131000"
      name: "気象情報:（2/26(水) 10:00-12:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T10:00:00+09:00"
      duration: 3h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    - id: "C4_202502131100"
      name: "気象情報:（2/26(火) 13:00-13:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T13:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "40.0"
        precipitation: "0.0"
    # 12:00, 13:00, 17:00リクエストのデータ
    - id: "C4_202502131200"
      name: "気象情報:（2/26(水) 14:00-20:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-26T14:00:00+09:00"
      duration: 7h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    # 14:00, 18:00リクエストのデータ
    - id: "C4_202502131400"
      name: "気象情報:（2/27(木) 09:00-12:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-27T09:00:00+09:00"
      duration: 4h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    - id: "C4_202502131500_1"
      name: "気象情報:（2/27(木) 14:00-14:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-27T14:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "15.0"
        precipitation: "0.0"
    - id: "C4_202502131500_2"
      name: "気象情報:（2/27(木) 15:00-16:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-27T15:00:00+09:00"
      duration: 2h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"