# 2025/02/21にリクエストされるデータ群
testdata:
  flushData: false
  data: []
  randomDataOutputDir: "./data/"
  # 個別設定で上書きするため以下の2つは使われない
  randomDataBaseTime: "2025-01-28T10:00:00+09:00"
  randomDataDuration: 1h
  randomData:
    - id: "C4_202502211000"
      name: "気象情報:（2/25(火) 14:00-16:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-25T14:00:00+09:00"
      duration: 3h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
    - id: "C4_202502211100_1"
      name: "気象情報:（2/25(火) 22:00-22:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-25T22:00:00+09:00"
      duration: 1h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "15.0"
        precipitation: "0.0"
    - id: "C4_202502211100_2"
      name: "気象情報:（2/25(火) 23:00-24:00のデータ）"
      templateType: Weather
      interval: 1h
      baseTime: "2025-02-25T23:00:00+09:00"
      duration: 2h
      updatedAtOffset: 1h
      areas:
        - boundingBoxes: []
          coordinate:
            # 藤枝岡部ICを含む空間IDの中央座標
            longitude: 138.2574462890625
            latitude: 34.9174668892
            altitude: 0.0
      staticAttributes:
        weatherForecast: "100"
        windSpeed: "0.0"
        precipitation: "0.0"
