testdata:
  flushData: false
  data:
    # 15/0/29183/12809の中心座標
    - key:
        time: "2024-11-12T10:00:00+09:00"
        longitude: 140.6195068359375
        latitude: 36.5140511994
        altitude: 1
        movingObjectId: "testdata"
      attributes:
        spatialId: "25/0/29883903/13116927"
        vehicleId: "8bde1f99-087e-4b5d-9a38-a1e68fd6e5e6"
        vehicleName: "vehicle1"
        status: "ready"
        height: "1"
        updatedAt: "2024-11-12T10:00:00+09:00"
    # 15/0/29183/12810の中心座標
    - key:
        time: "2024-11-12T10:00:00+09:00"
        longitude: 140.6195068359375
        latitude: 36.5052208633
        altitude: 1
        movingObjectId: "testdata"
      attributes:
        spatialId: "25/0/29883903/13117951"
        vehicleId: "da98d6ae-069f-434a-a6fd-741328eaf91c"
        vehicleName: "vehicle2"
        status: "ready"
        height: "1"
        updatedAt: "2024-11-12T10:00:00+09:00"
    # 15/0/29183/12809の中心座標
    - key:
        time: "2024-11-12T10:00:00+09:00"
        longitude: 140.6195068359375
        latitude: 36.5140511994
        altitude: 1
        movingObjectId: "testdata-target1"
      attributes:
        spatialId: "25/0/29883903/13116927"
        time: "2024-11-12T10:00:00+09:00"
        targetID: "1234567891"
        latitude: "365140511"
        longitude: "1406195068"
        elevation: "1"
        elevationConf: "2"
        positionConf: "1"
        speed: "1234"
        heading: "14400"
        acceleration: "123"
        speedConf: "1"
        headingConf: "1"
        forwardRearAccelerationConf: "1"
        sizeClassification: "2"
        roleClassification: "1"
        vehicleWidth: "140"
        vehicleLength: "180"
        semiMajorAxisOfPositionalErrorEllipse: "15"
        semiMinorAxisOfPositionalErrorEllipse: "15"
        semiMajorAxisOrientationOfPositionalErrorEllipse: "7200"
        GPSPositioningMode: "1"
        GPSPDOP: "12"
        restingState: "12"
    # 15/0/29183/12810の中心座標
    - key:
        time: "2024-11-12T10:00:00+09:00"
        longitude: 140.6195068359375
        latitude: 36.5052208633
        altitude: 1
        movingObjectId: "testdata-taget2"
      attributes:
        spatialId: "25/0/29883903/13117951"
        time: "2024-11-12T10:00:00+09:00"
        targetID: "1234567892"
        latitude: "365052208"
        longitude: "1406195068"
        elevation: "1"
        elevationConf: "2"
        positionConf: "1"
        speed: "1234"
        heading: "14400"
        acceleration: "123"
        speedConf: "1"
        headingConf: "1"
        forwardRearAccelerationConf: "1"
        sizeClassification: "2"
        roleClassification: "1"
        vehicleWidth: "140"
        vehicleLength: "180"
        semiMajorAxisOfPositionalErrorEllipse: "15"
        semiMinorAxisOfPositionalErrorEllipse: "15"
        semiMajorAxisOrientationOfPositionalErrorEllipse: "7200"
        GPSPositioningMode: "1"
        GPSPDOP: "12"
        restingState: "12"
