# 2025/02/19の物標ダミーデータ
testdata:
  flushData: false
  data: []
  randomDataOutputDir: "./data/"
  randomDataBaseTime: "2025-02-19T08:00:00+09:00"
  randomDataDuration: 14h # 22時まで
  randomData:
    - id: "C1_20250219"
      name: "物標情報:（2/19(水) 08:00-22:00のデータ）"
      templateType: Target
      interval: 60m
      areas:
        - boundingBoxes: []
          coordinate:
            # 指定された値から分解能を考慮した座標
            longitude: 140.62823
            latitude: 36.511718
            altitude: 0
      staticAttributes:
        targetID: "1234567890"
        speed: "0"
        sizeClassification: "2"
        roleClassification: "0"
        restingState: "300"
