variable "env" {}
variable "vpc_id" {}
variable "space_private_azA_cidr" {}
variable "space_private_azC_cidr" {}
variable "collection_private_azA_cidr" {}
variable "vdl_private_azA_cidr" {}
variable "vdl_private_azC_cidr" {}
variable "vdl_vpc_endpoint_ecr_api" {}
variable "vdl_vpc_endpoint_ecr_dkr" {}
